### PR TITLE
Added pt_BR internationalization files

### PR DESCRIPTION
**Pull request by 2aces**
## Description
Added pt_BR (Brazilian Portuguese) i18n files

## How Has This Been Tested?
Local, development and production sites like www.celsobessa.com.br, www.japuapp.com.br and www.superlumina.com.br

### CODE REVIEW

**Comment by DevinWalker** [comment]
Hi @2aces - since this is a WP.org plugin we kindly ask that you submit your translations over here: https://translate.wordpress.org/projects/wp-plugins/wp-rollback

Thanks! :)

**Comment by 2aces** [comment]
No problem. Can you add the user celsobessa as PTE so I can import/export without waiting approval?

Thanks in advance

**Comment by DevinWalker** [comment]
Hey @2aces I don't think I can do that myself. I think it has to be an admin over on the WP.org site. Please correct me if I'm wrong.

**Comment by 2aces** [comment]
@DevinWalker you are right. I am sorry I didn't made myself clear.

As per this post https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#requesting-new-translation-editors , the plugin author is the one that makes the request to turn an user ( celsobessa in this case) a PTE for a plugin locale.

I already submitted the stable string there and they are waiting for approval. When I become PTE I will translate the dev and the readme faster. :-)

Thanks again!

**Pull request closed without merging**
